image: docker:stable-git

stages:
  - build
  - deploy

before_script:
  - git checkout -B "$CI_BUILD_REF_NAME" "$CI_BUILD_REF"

Build:
  only:
    - master
  stage: build
  script:
    - docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p$CI_REGISTRY_PASSWORD
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA $DIRECTORY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

Déploiement:
  only:
    - master
  stage: deploy
  environment:
    name: Master
    url: https://caroster.test.octr.ee
  image: nexus.octree.ch/ci/kubectl
  script:
    - find k8s/ -type f | xargs sed -i "s~<TAG>~$CI_COMMIT_SHORT_SHA~g"
    - kubectl apply -Rf k8s/ -n $NAMESPACE
