
swagger: "2.0"
info:
  description: "API de covoiturage"
  version: "1.0.0"
  title: "Caroster"

host: "caroster.test.octr.ee"
basePath: "/api"

schemes:
- "https"
- "http"
paths:
  /event:
    post:
      summary: "Créer evenement"
      description: ""
      operationId: "ajouterEvenement"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
        schema:
          $ref: "#/definitions/Event"
      responses:
        405:
          description: "Input ne pas valide"
    get:
      summary: "Liste d'evenements"
      description: ""
      responses:
        200:
          description: "Liste d'evenements"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Evenement non trouvé"
  
  /event/{eventId}:
    get:
      summary: "Trouver evenement par son ID"
      description: ""
      operationId: "getEventById"
      produces:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        description: "ID d'evenement"
        required: true
        type: "string"
      responses:
        200:
          description: "Operation réussie"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Evenement non trouvé"
    post:
      summary: "Modifier les données d'evenement"
      description: ""
      operationId: "updateEventWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "eventId"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name:  "nom"
        in: "formData"
        description: "Mise a jour nom d'evenement"
        required: false
        type: "string"
      - name:  "email"
        in: "formData"
        description: "Mise a jour email d'evenement"
        required: false
        type: "string"
      responses:
        405:
          description: "Input ne pas valide"
    delete:
      summary: "Supprimer evenement"
      description: ""
      operationId: "deleteEvenement"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "eventId"
        in: "path"
        description: ""
        required: true
        type: "string"
      responses:
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Evenement non trouvé"
        
  /event/car:
    post:
      summary: "Ajouter voiture a l'evenement"
      description: ""
      operationId: "addVoiture"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Ajoute une voiture"
        required: true
        schema:
          $ref: "#/definitions/Car"
      responses:
        405:
          description: "Input ne pas valide"
      
  /event/car/list:      
    get:
      summary: "Liste des voitures"
      description: ""
      responses:
        200:
          description: "Liste des voitures"
          schema:
            $ref: "#/definitions/Car"
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Voiture non trouvé"
  
  /event/car/{carId}:
    get:
      summary: "Trouver voiture par son ID"
      description: " "
      operationId: "getCarById"
      produces:
      - "application/json"
      parameters:
      - name: "carId"
        in: "path"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "Operation réussie"
          schema:
            $ref: "#/definitions/Car"
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Voiture non trouvé"
    post:
      summary: "Modifier les données de la voiture"
      description: ""
      operationId: "updateVoitureWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "carId"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "nom"
        in: "formData"
        description: "Mise a jour nom de la voiture"
        required: false
        type: "string"
      - name: "sieges"
        in: "formData"
        description: "Mise a jour sieges de la voiture"
        required: false
        type: "number"
      - name: "info complementaires"
        in: "formData"
        description: "Mise a jour info complementaires voiture"
        required: false
        type: "string"
      - name: "contact proprietaire"
        in: "formData"
        description: "Mise a jour contact proprietaire voiture"
        required: false
        type: "string"
      - name: "adresse"
        in: "formData"
        description: "Mise a jour adresse lieu rendez-vous"
        required: false
        type: "string"
      - name: "date"
        in: "formData"
        description: "Mise a jour date de rendez-vous"
        required: false
        type: "string"
      - name: "heure"
        in: "formData"
        description: "Mise a jour heure du rendez-vous"
        required: false
        type: "string"
      responses:
        405:
          description: "Input ne pas valide"
    delete:
      summary: "Supprimer Voiture"
      description: ""
      operationId: "deleteVoiture"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "carId"
        in: "path"
        description: "supprime la voiture par son ID"
        required: true
        type: "string"
      responses:
        400:
          description: "ID fournie ne pas valide"
      
  /event/car/passengers:
    post:
      summary: "Ajouter passagers"
      description: ""
      operationId: "addPassagers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Ajoute passager dans la voiture"
        required: true
        schema:
          $ref: "#/definitions/Passengers"
      responses:
        405:
          description: "Input ne pas valide"

  /event/car/passengers/{passengersId}:
    get:
      summary: "Trouver passagers par son ID"
      description: ""
      operationId: "getPassagersById"
      produces:
      - "application/json"
      parameters:
      - name: "passengersId"
        in: "path"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "Operation réussie"
          schema:
            $ref: "#/definitions/Passengers"
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Passagers non trouvé"
    post:
      summary: "Modifier les données du passagers"
      description: ""
      operationId: "updatePassagersWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "passengersId"
        in: "path"
        description: "ID du passagres"
        required: true
        type: "string"
      - name:  "nom"
        in: "formData"
        description: "Mise a jour nom du passagers"
        required: false
        type: "string"
      responses:
        405:
          description: "Input ne pas valide"
    delete:
      summary: "Supprimer passagers"
      description: ""
      operationId: "deletePassager"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "passengersId"
        in: "path"
        description: "Passagers Id a supprimer"
        required: true
        type: "string"
      responses:
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Passagers non trouvé"
     
  /event/car/passengers/list:      
    get:
      summary: "Liste des passagers"
      description: ""
      responses:
        200:
          description: "Operation réussie"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Passagers non trouvé"
          
  /event/passengers:
    post:
      summary: "Ajouter passagers"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Ajoute passager dans la voiture"
        required: true
        schema:
          $ref: "#/definitions/Passengers"
      responses:
        405:
          description: "Input ne pas valide"

  /event/passengers/{passengersId}:
    get:
      summary: "Trouver passagers par son ID"
      description: ""
      operationId: "PassagersId"
      produces:
      - "application/json"
      parameters:
      - name: "passengersId"
        in: "path"
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "Operation réussie"
          schema:
            $ref: "#/definitions/Passengers"
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Passagers non trouvé"
    post:
      summary: "Modifier les données du passagers"
      description: ""
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "passengersId"
        in: "path"
        description: "ID du passagres"
        required: true
        type: "string"
      - name:  "nom"
        in: "formData"
        description: "Mise a jour nom du passagers"
        required: false
        type: "string"
      responses:
        405:
          description: "Input ne pas valide"
    delete:
      summary: "Supprimer passagers"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "passengersId"
        in: "path"
        description: "Passagers Id a supprimer"
        required: true
        type: "string"
      responses:
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Passagers non trouvé"
     
  /event/passengers/list:      
    get:
      summary: "Liste des passagers"
      description: ""
      responses:
        200:
          description: "Operation réussie"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "ID fournie ne pas valide"
        404:
          description: "Passagers non trouvé"
   
definitions:
  Event:
    type: "object"
    required:
    - "titre"
    - "email"
    properties:
      id:
        type: "string"
      titre:
        type: "string"
      email:
        type: "string"
      car:
        type: "array"
        items:
         $ref: '#/definitions/Car'
      passengers:
        type: "array"
        items:
         $ref: '#/definitions/Passengers'
  Car:
    type: "object"
    required: 
    - "nom"
    - "sieges"
    - "contact proprietaire"
    - "adresse"
    - "date"
    - "horaire"
    properties:
      id:
        type: "string"
      nom:
        type: "string"
      sieges:
        type: "number"
      info complementaires:
        type: "string"
      contact proprietaire:
        type: "string"
      adresse: 
        type: "string"
      date:
        type: "string"
      horaire:
        type: "string"
      passengers:
       type: "array"
       items:
         $ref: '#/definitions/Passengers'
  Passengers:
    type: "object"
    required: 
    - "nom"
    properties:
      id:
        type: "string"
      nom:
        type: "string"
   
